package PerlForums::App::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'PerlForums::App::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:Forums',
        user => 'root',
        password => '',
    }
);

=head1 NAME

PerlForums::App::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<PerlForums::App>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<PerlForums::App::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Ashutosh Kukreti

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
